- name: Download Brave GPG key
  ansible.builtin.get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
    mode: "0644"
  become: true

- name: Create Brave repository file if needed
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/brave-browser-release.list
    state: touch
    mode: "0644"
  become: true

- name: Add Brave repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/brave-browser-release.list
    line: "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"
    state: present
  become: true

- name: Update the APT cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install Brave browser
  ansible.builtin.apt:
    name: brave-browser
    state: present
  become: true
