- name: Setup desktop hosts
  hosts: desktop

  roles:
    - role: system
    - role: desktop_environment
    - role: dev_environment

- name: Run administration setup tasks for desktop hosts
  hosts: desktop
  roles:
    - role: geerlingguy.security
    - role: geerlingguy.docker
    - role: geerlingguy.nodejs
  become: true
