system_packages:
  - neovim
  - htop
  - btop
  - git
  - ca-certificates
  - curl
  - wget
  - neofetch
  - ufw
  - fail2ban
  - openssh-server
  - python3-dev
  - python3-pip
  - kitty
  - cmake
  - ninja-build
  - libfuse2
  - libxi6
  - libxrender1
  - libxtst6
  - mesa-utils
  - libfontconfig
  - libgtk-3-bin
  - tar
  - dbus-user-session
  - unzip
  - xclip
  - libfuse2t64
  - libc6
  - libgcc1
  - libgssapi-krb5-2
  - libssl3
  - libstdc++6
  - zlib1g
  - libglu1-mesa
  - lib32z1
  - libbz2-1.0
  - python3-psutil
  - fonts-jetbrains-mono
  - fish
